export const designTokens = {
  colors: {
    primary: 'var(--color-primary)',
    primaryForeground: 'var(--color-primary-foreground)',
    secondary: 'var(--color-secondary)',
    secondaryForeground: 'var(--color-secondary-foreground)',
    neutral: 'var(--color-neutral)',
    neutralForeground: 'var(--color-neutral-foreground)',
    success: 'var(--color-success)',
    successForeground: 'var(--color-success-foreground)',
    warning: 'var(--color-warning)',
    warningForeground: 'var(--color-warning-foreground)',
    error: 'var(--color-error)',
    errorForeground: 'var(--color-error-foreground)',
    info: 'var(--color-info)',
    infoForeground: 'var(--color-info-foreground)',
  },
  typography: {
    heading: 'var(--font-heading)',
    body: 'var(--font-body)',
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
  },
  spacing: {
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    8: '2rem',
    10: '2.5rem',
    12: '3rem',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
  },
  shadows: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
  },
  zIndex: {
    dropdown: 'var(--z-dropdown)',
    sticky: 'var(--z-sticky)',
    overlay: 'var(--z-overlay)',
    modal: 'var(--z-modal)',
    toast: 'var(--z-toast)',
  },
} as const
